version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootroot

  air-management:
    image: air-manager:001
    restart: always
    ports:
      - "9090:8080"
    depends_on:
      - db